version: '3.4'

services:
  sandbox:
    image: senwize/sandbox
    scale: 3
    build:
      context: docker
      dockerfile: sandbox.Dockerfile
      args:
        ARG_MERGE_STAGE_VNC_BASE: stage_vnc
        ARG_MERGE_STAGE_BROWSER_BASE: stage_firefox
        ARG_FINAL_STAGE_BASE: stage_vscode
        ARG_HEADLESS_USER_NAME: workshop
        ARG_SUDO_PW: workshop
        ARG_VNC_PORT: 5901
        ARG_VNC_PW: workshop
        ARG_VNC_RESOLUTION: '1920x1080'
        ARG_VNC_COL_DEPTH: '16'
    privileged: true
    hostname: sandbox.remoto.local
    # ports: # password = headless
    #   - '5901:5901'

  guacd:
    image: guacamole/guacd:1.4.0
    hostname: guacd.remoto.local

  remoto:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: ['reflex', '-r', '\.go', '-s', 'go', 'run', 'main.go', 'serve']
    working_dir: /app
    environment:
      REMOTO_GUACD_FQDN: guacd.remoto.local
      REMOTO_SANDBOX_FQDN: sandbox.remoto.local
      REMOTO_HTTP_ADDR: 0.0.0.0:3000
      REMOTO_WORKSHOP_CODE: demo
      REMOTO_ADMIN_CODE: admin
    ports:
      - '3000:3000'
    volumes:
      - ./:/app

  remoto_client:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: ['npm', 'run', 'dev']
    working_dir: /app/client
    volumes:
      - ./:/app
